spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#    loadbalancer:
#      ribbon:
#        enabled: false
#  cloud:
#    gateway:
#      routes:
#        - id: order-service
#          uri: lb://CLIENT-SERVICE
#          predicates:
#            - Path=/**
server:
  port: 8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/